name: Checking AS02 Build

on:
  push:
    branches:
      - main

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Check number of branches
        run: |
          git fetch --all
          git branch -r | grep -v main | wc -l # Check for non-main branches

      - name: Check commit history
        run: |
          git log --oneline | wc -l # Check number of commits

      - name: Validate CI workflow file
        run: |
          if [ -f ".github/workflows/CI.yml" ]; then
            echo "CI pipeline file found."
          else
            echo "CI pipeline file is missing."
            exit 1
          fi

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn test

      - name: Build Docker image
        run: |
          docker build -t musicfinder .
          docker run -d -p 8080:8080 musicfinder &
          sleep 10
      
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.organization=seanquinn21 -Dsonar.projectKey=seanquinn21_assignment2 -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${{ secrets.SONAR_TOKEN }}


env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
